/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HP' at '6/10/20 11:05 AM' with Gradle 2.14.1
 *
 * @author HP, @date 6/10/20 11:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
